DROP TABLE IF EXISTS banks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS places;

CREATE TABLE IF NOT EXISTS banks
(
  id   INTEGER AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (name)
  );

CREATE TABLE IF NOT EXISTS cards
(
  id   INTEGER AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  bank_id INTEGER NOT NULL,
  FOREIGN KEY (bank_id) REFERENCES banks (id)
);

CREATE TABLE IF NOT EXISTS category
(
  id       INTEGER AUTO_INCREMENT,
  card     VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS places
(
  id   INTEGER AUTO_INCREMENT,
  mcc  INTEGER(5)   NOT NULL,
  name VARCHAR(255) NOT NULL
);