DROP TABLE IF EXISTS banks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS places;

CREATE TABLE IF NOT EXISTS banks
(
  id   INTEGER AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cards
(
  id      INTEGER,
  name    VARCHAR(255) NOT NULL,
  bank_id INTEGER      NOT NULL,
  FOREIGN KEY (bank_id) REFERENCES banks (id),
  PRIMARY KEY (bank_id, id)
);

CREATE TABLE IF NOT EXISTS category
(
  id      INTEGER AUTO_INCREMENT PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  mcc     INTEGER      NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CARDS_CATEGORY
(
  CARD_ID     INTEGER,
  BANK_ID     INTEGER,
  CATEGORY_ID INTEGER
);

ALTER TABLE CARDS_CATEGORY
  ADD CONSTRAINT CARDS_CATEGORY_FK FOREIGN KEY (CARD_ID,BANK_ID) REFERENCES cards (id,bank_id);
ALTER TABLE CARDS_CATEGORY
  ADD CONSTRAINT CARDS_CARDS_FK FOREIGN KEY (CATEGORY_ID) REFERENCES category (id);

CREATE TABLE IF NOT EXISTS places
(
  id   INTEGER AUTO_INCREMENT,
  mcc  INTEGER(5)   NOT NULL,
  name VARCHAR(255) NOT NULL
);